### ISSUE TITLE
Model weights cannot be downloaded (`This repository is over its data quota`)

### ISSUE THREAD

**Issue by nvladimus** [AlbertPun/TRAILMAP#14]
Hi, everyone,
I tried to install Trailmap, but unfortunately got the following error:
```
Downloading data/model-weights/trailmap_model.hdf5 (229 MB)
Error downloading object: data/model-weights/trailmap_model.hdf5 (f866d8c): 
Smudge error: Error downloading data/model-weights/trailmap_model.hdf5 (f866d8c068a52fc6c07fbbdebb2dc63d2c678a45936111fcf62ca4351aa3537d): 
batch response: This repository is over its data quota. 
Account responsible for LFS bandwidth should purchase more data packs to restore access.
```
Is there a way to download the model weights?
Thank you!

**Comment by dfriedma** [comment]
Just realized this is the same conversation coming over from Twitter! It looks like the Google quota is based on downloads/day. I just confirmed that I was able to download it today (07/20/21) so it will be worth trying again later. However, I will work on getting it hosted in a more permanent space (e.g. Dryad).
