### ISSUE TITLE
`get_dir` gets thrown off by created `seg-` folder

### ISSUE THREAD

**Issue by VolkerH** [AlbertPun/TRAILMAP#5]
After sorting out the issues with tensorflow and our 2080Ti card I ran into the following issue
when trying to segment the testing volume.

```
2020-02-13 15:10:59.996792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10080 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5)
data/testing/example-chunk/seg- already exists. Will be overwritten
Name:
[=================================       ]  83%       ETA: 0.0 mins       Traceback (most recent call last):
  File "segment_brain_batch.py", line 40, in <module>
    segment_brain(input_folder, output_folder, model)
  File "/home/vhil0002/Github/tmp/TRAILMAP/inference/segment_brain.py", line 146, in segment_brain
    section = read_folder_section(input_folder, end_aligned, end_aligned + input_dim).astype('float32')
ValueError: setting an array element with a sequence.
```

I was able to trace this down to the following lines of code:

https://github.com/AlbertPun/TRAILMAP/blob/84479bb62fc5ffedcf3010d1e1604c4bdb2a9ef6/inference/segment_brain.py#L31-L33

It turns out that TRAILMAP creates a `seg-` subfolder in the folder with the images. This folder gets added to the list of tiff files returned by `get_dir(...)`.

My quick and dirty workaround was to modify the line as follows:

```
    tiffs = [os.path.join(path, f) for f in os.listdir(path) if f[0] != '.' and f.endswith('.tif')]
```
This is not ideal as it excludes `.tiff`, `.TIF`, `.png` etc. but it was good enough to get it working.

**Comment by albert597** [comment]
To make sure I am understanding this right, when you ran segment_brain_batch.py on our example-chunk, the seg-example-chunk folder was inside the example-chunk folder?

**Comment by VolkerH** [comment]
Yes, that is correct. And it only was called `seg-` (without the `-examaple-chunk` bit at the end. 
This is invoking the example from the top-level folder of the repo using the command given in the readme. 
Note however, that I previously also experienced a different behaviour (with the new folder created at the same level as the `example-chunk` folder). However, I don't recall what I did differently then (maybe invoked the command from a different working directory). 
In any case it is working for me now when I restrict reading to tiff files.

**Comment by VolkerH** [comment]
closed by accident (clicked the wrong button).

**Comment by albert597** [comment]
This is very weird behavior. I will try to recreate the issue and find out why this could be happening. Thank you for finding this issue.

Please let me know if you have anymore concerns.

**Comment by albert597** [comment]
Sorry for the delay, but I found the issue was due to trailing slashes in the input_folder name. I have fixed the issue now.

**Comment by VolkerH** [comment]
Thanks

**Comment by VolkerH** [comment]
just a comment ... I highly recommend using `pathlib.Path` instead of `os.path` functionality these days, as it basically eliminates this sort of error.
