### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by adamltyson** [AlbertPun/TRAILMAP#6]
Hi @AlbertPun,

This project looks awesome, and it's related to some stuff we're doing for whole brain image registration, cell detection, standard space analysis and visualisation (e.g. [cellfinder](https://github.com/sainsburywellcomecentre/cellfinder)). What we don't have however is a good way to segment axons in these datasets.

I have a couple of questions:
* Have you tried applying trailmap to other imaging modalities? I particularly want to try with some of our serial two-photon data.
* Do you have any plans for releasing trailmap as e.g. a package on PyPI? If possible I would love to make our tools interoperable with trailmap, and move towards an integrated toolset for the analysis of whole-brain images.

I couldn't find your email, but if you want to carry on this conversation via email, my address is `adam.tyson@ucl.ac.uk`.

Thanks!
Adam

**Comment by dfriedma** [comment]
Hi Adam-
It does indeed work with other imaging modalities as well as other biological structures (eg. small diameter vasculature). Our revised manuscript includes some of these examples and I'll get in touch with you over email to see if there are any particular considerations or concerns for your data type.
--Drew
