### ISSUE TITLE
Hi, your work is good, and where can I find your training dataset?

### ISSUE THREAD

**Issue by LLveSzy** [AlbertPun/TRAILMAP#7]

**Comment by dfriedma** [comment]
Thanks!
We'll merge together all our training data and get it uploaded soon. The set has been growing and evolving recently to better capture dense projection patterns.

**Comment by LLveSzy** [comment]
> Thanks!
> We'll merge together all our training data and get it uploaded soon. The set has been growing and evolving recently to better capture dense projection patterns.

It's very kind of you.
I'll always come back for updates. It will be helpful to me.

**Comment by LLveSzy** [comment]
> Thanks!
> We'll merge together all our training data and get it uploaded soon. The set has been growing and evolving recently to better capture dense projection patterns.

It's very kind of you.
I'll often come back to your updates. It will be helpful to me.

**Comment by LLveSzy** [comment]
Dear @AlbertPun and @dfriedma ,

 I'm still here, coming for updates. :(

**Comment by dfriedma** [comment]
Added a google drive link to the extended readme containing the original training set. I haven't yet added in the newer annotations because I'm not yet pleased with the performance and haven't solved why, hence the delay.
Hope this helps!

**Comment by LLveSzy** [comment]
> Added a google drive link to the extended readme containing the original training set. I haven't yet added in the newer annotations because I'm not yet pleased with the performance and haven't solved why, hence the delay.
> Hope this helps!

Thank you very much!
Excuse my ignorance, can this model train a powerful network with a data set of fewer than 100 labeled graphs? It's surprising. :D

**Comment by LLveSzy** [comment]
> Added a google drive link to the extended readme containing the original training set. I haven't yet added in the newer annotations because I'm not yet pleased with the performance and haven't solved why, hence the delay.
> Hope this helps!

Thank you very much!
Excuse my ignorance, can this model train a powerful network with a data set of fewer than 100 labeled volumes? It's surprising. :D
