### ISSUE TITLE
Error during inference

### ISSUE THREAD

**Issue by auesro** [AlbertPun/TRAILMAP#8]
Hi @AlbertPun and @dfriedma ,
I ALMOST succesfully inferred my own half brain stack with your network (I have had no problems with the test dataset provided).
However, this error came up almost at the end:
```
2020-05-13 16:52:32.160325: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
Name: 200507_1034_561_080X_Dynamic_12-05-45
[                                        ]   0%       ETA: Pending        2020-05-13 16:52:34.550799: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-13 16:52:35.416072: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
[=====================================   ]  94%       ETA: 1.4 mins       TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "segment_brain_batch.py", line 43, in <module>
    segment_brain(input_folder, output_folder, model)
  File "/home/augustoer/TRAILMAP/inference/segment_brain.py", line 121, in segment_brain
    section = read_folder_section(input_folder, section_index, section_index + input_dim).astype('float32')
ValueError: setting an array element with a sequence.
```
Any ideas on how to fix it?

Thanks

A

**Comment by dfriedma** [comment]
Could you check two things? 
-Given that you reached 94%, it's probable that you have written a folder with most of the segmentation already complete, but it is likely missing the last ~50 slices. If not, let me know because the issue is likely deeper.
-Are there any other files in the folder with your raw data? In particular, anything alphanumerically _after_ all the names for the TIFFs.

**Comment by auesro** [comment]
Silly me...there is a Thumbs.db Windows file....
Let me re-run the network and see but I am pretty sure this is the problem (stupid Windows!), thanks a lot! 
I will report back in a few minutes

A

**Comment by auesro** [comment]
Yes, exactly as predicted. Beware of Windows hidden Thumbs.db files present in each and every folder!

Thanks again, @dfriedma 

A
